import { createConstants } from 'utils';

export default createConstants(
  'ADDING_TRACK',
  'ADD_TRACK_SUCCESS',
  'GET_CURRENT_TRACK',
  'GET_PLAYLIST',
  'GET_PLAYLIST_SUCCESS',
  'FETCH_FIREBASE',
  'FETCH_FIREBASE_SUCCESS',
  'NEXT_TRACK',
  'SET_CURRENT_TRACK',
  'SET_CURRENT_TRACK_SUCCESS',
  'SET_FIREBASE',
  'SET_FIREBASE_SUCCESS',
  'SET_PLAYLIST',
  'SET_PLAYLIST_SUCCESS',
  'REMOVE_TRACK'
);
