import {createConstants} from 'utils';

export default createConstants(
	'AVAILABILITY_REQUEST',
	'AVAILABILITY_RECEIVED',
  'GET_SCHEDULE',
  'GET_ROOM_STATUS',
  'ROOM_STATUS_ERROR',
  'ROOM_STATUS_REQUEST',
  'ROOM_STATUS_RECEIVED',
  'DATE_LOOKUP_REQUEST',
  'DATE_LOOKUP_RECEIVED',
  'SCHEDULE_REQUEST',
  'SCHEDULE_RECEIVED',
  'USER_LIST_REQUEST',
  'USER_LIST_RECEIVED'
);
